name: NodeJS with Grunt
npm publishnpm run deploynpm run testnpm run build# To check lint errors
npm run lint

# To fix most common lint errors
# Note that it might not fix all errors, some need manual intervention
npm run lint:fixnpm run debugnpm ci            - name: Setup Node.js environment
  uses: actions/setup-node@v3.9.1
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
          https://verbose-umbrella-69pvq74x46v43xv4p.github.dev/[![Process new comment on issue](https://github.com/microsoft/WSL/actions/workflows/new_issue_comment.yml/badge.svg)](https://github.com/microsoft/WSL/actions/workflows/new_issue_comment.yml)install.\collect-wsl-logs.ps1https://github.com/microsoft/WSL/issues/13248Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1wsl --installhttps://github.com/microsoft/WSL/issues/13248Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/WSL/master/diagnostics/collect-wsl-logs.ps1" -OutFile collect-wsl-logs.ps1
Set-ExecutionPolicy Bypass -Scope Process -Force
.\collect-wsl-logs.ps1git clone --depth=1 https://github.com/coinbase/cdp-sdk && cd cdp-sdk/examples/typescript/quickstart# bash curl -X POST https://rpc.ankr.com/eth/64df6edab9e914be234827cf9cc077b56ac4cea9d88e5e41cfdc5515d6ed04a9 -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'curl --location 'https://proportionate-side-glade.quiknode.pro/8913b2ad07a291ca123c31ada7dede759d25622a' \
--header 'Content-Type: application/json' \
--data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'# bash
curl -X POST https://rpc.ankr.com/eth/64df6edab9e914be234827cf9cc077b56ac4cea9d88e5e41cfdc5515d6ed04a9 -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'# bash curl -X POST https://rpc.ankr.com/eth/64df6edab9e914be234827cf9cc077b56ac4cea9d88e5e41cfdc5515d6ed04a9 -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'https://proportionate-side-glade.quiknode.pro/8913b2ad07a291ca123c31ada7dede759d25622acurl --location 'https://proportionate-side-glade.quiknode.pro/8913b2ad07a291ca123c31ada7dede759d25622a' \
--header 'Content-Type: application/json' \
--data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'https://rpc.ankr.com/multichain/# bash
curl -X POST https://rpc.ankr.com/eth/64df6edab9e914be234827cf9cc077b56ac4cea9d88e5e41cfdc5515d6ed04a9 -d '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'Ethereum RPC endpoints
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        grunt
